/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface MenuNav {}
  interface MenuTabs {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMenuNavElement extends Components.MenuNav, HTMLStencilElement {}
  var HTMLMenuNavElement: {
    prototype: HTMLMenuNavElement;
    new (): HTMLMenuNavElement;
  };

  interface HTMLMenuTabsElement extends Components.MenuTabs, HTMLStencilElement {}
  var HTMLMenuTabsElement: {
    prototype: HTMLMenuTabsElement;
    new (): HTMLMenuTabsElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'menu-nav': HTMLMenuNavElement;
    'menu-tabs': HTMLMenuTabsElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface MenuNav {}
  interface MenuTabs {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'menu-nav': MenuNav;
    'menu-tabs': MenuTabs;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'menu-nav': LocalJSX.MenuNav & JSXBase.HTMLAttributes<HTMLMenuNavElement>;
      'menu-tabs': LocalJSX.MenuTabs & JSXBase.HTMLAttributes<HTMLMenuTabsElement>;
    }
  }
}


