/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface MenuNav {}
  interface MenuTabs {}
  interface ScreenFirebase {}
  interface ScreenLogin {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMenuNavElement extends Components.MenuNav, HTMLStencilElement {}
  var HTMLMenuNavElement: {
    prototype: HTMLMenuNavElement;
    new (): HTMLMenuNavElement;
  };

  interface HTMLMenuTabsElement extends Components.MenuTabs, HTMLStencilElement {}
  var HTMLMenuTabsElement: {
    prototype: HTMLMenuTabsElement;
    new (): HTMLMenuTabsElement;
  };

  interface HTMLScreenFirebaseElement extends Components.ScreenFirebase, HTMLStencilElement {}
  var HTMLScreenFirebaseElement: {
    prototype: HTMLScreenFirebaseElement;
    new (): HTMLScreenFirebaseElement;
  };

  interface HTMLScreenLoginElement extends Components.ScreenLogin, HTMLStencilElement {}
  var HTMLScreenLoginElement: {
    prototype: HTMLScreenLoginElement;
    new (): HTMLScreenLoginElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'menu-nav': HTMLMenuNavElement;
    'menu-tabs': HTMLMenuTabsElement;
    'screen-firebase': HTMLScreenFirebaseElement;
    'screen-login': HTMLScreenLoginElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface MenuNav {}
  interface MenuTabs {}
  interface ScreenFirebase {}
  interface ScreenLogin {
    'onUserDidLogIn'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'app-root': AppRoot;
    'menu-nav': MenuNav;
    'menu-tabs': MenuTabs;
    'screen-firebase': ScreenFirebase;
    'screen-login': ScreenLogin;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'menu-nav': LocalJSX.MenuNav & JSXBase.HTMLAttributes<HTMLMenuNavElement>;
      'menu-tabs': LocalJSX.MenuTabs & JSXBase.HTMLAttributes<HTMLMenuTabsElement>;
      'screen-firebase': LocalJSX.ScreenFirebase & JSXBase.HTMLAttributes<HTMLScreenFirebaseElement>;
      'screen-login': LocalJSX.ScreenLogin & JSXBase.HTMLAttributes<HTMLScreenLoginElement>;
    }
  }
}


